### PR TITLE
352-unclickable-project-buttons

### PR DESCRIPTION
**Pull request by waltersajtos**
## Description

The alert-container was blocking the edit and delete button

## Type of change

-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

## Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [x] I updated the changelog with an end-user readable description
-   [x] I assigned this pull request to the correct project board to update the sprint board

## Steps to Test or Reproduce

Outline the steps to test or reproduce the PR here.
These steps will be used during release testing.

1. Create a project
2. After you get redirected to the project page, close the alert and try to click the delete button
3. The button should be clickable

## #352 

Closes: #352

### CODE REVIEW

**Review by niraymak — APPROVED** [review]
👍

**Comment by Brend-Smits** [comment]
Changelog 🙃

**Review by Ruby77 — APPROVED** [review]
Looks and works good👍

**Review by Brend-Smits — APPROVED** [review]
Works like a charm 👍

**Pull request merged**
