### PR TITLE
Updated favicon

### PR DESCRIPTION
**Pull request by rubenb994**
## Description

Update favicon to DeX logo X.

## Type of change
-   [x] Enhancement
-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

## Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I did not update API Controllers, if I did, I added/changed Postman tests
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes
-   [ ] I updated the changelog with an end-user readable description
-   [x] I assigned this pull request to the correct project board to update the sprint board

## Steps to Test or Reproduce
1. Run DeX project
2. See the new favicon

## Link to issue

Closes: #145

### CODE REVIEW

**Comment by Brend-Smits** [comment]
I'm pretty sure we need different sizes of the favicon for different browsers/operating systems. I think @MaxKorlaar has more knowledge about this topic so I will assign him as a reviewer.

**Comment by Brend-Smits** [comment]
Also, changelog :)

**Comment by rubenb994** [comment]
> Also, changelog :)

This seems completely unnecessary. Why would we want to reflect in our changelog that we changed the favicon? This doesn't seem useful at all to the end user.

**Comment by rubenb994** [comment]
> I'm also a big fan of https://realfavicongenerator.net/ for generating all sorts of standard sizes for various devices.

So we want to add all these support features?
`<link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">`

**Comment by MaxKorlaar** [comment]
> > I'm also a big fan of https://realfavicongenerator.net/ for generating all sorts of standard sizes for various devices.
> 
> So we want to add all these support features?
> 
> ```
> <link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon.png">
> <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
> <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
> <link rel="manifest" href="/site.webmanifest">
> <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
> <meta name="msapplication-TileColor" content="#da532c">
> <meta name="theme-color" content="#ffffff">
> ```

That's what I do on all my sites, yeah. Makes the icon show up on mobile devices, when pinning the tab in safari (See the Twitter example below) and on iOS and Android nicely.

image

Personally I'd place all those images in a `images/icons` or `images/favicons` folder in order to prevent cluttering our folders with these icons. That's what I do with my sites as well.

**Comment by Brend-Smits** [comment]
> > Also, changelog :)
> 
> This seems completely unnecessary. Why would we want to reflect in our changelog that we changed the favicon? This doesn't seem useful at all to the end user.

It might indeed not be useful for all end users, however, the changelog is both for the end-user and for our own housekeeping. It gives us an easy way to track changes as well. It's a small effort anyways..

**Comment by rubenb994** [comment]
> > > Also, changelog :)
> > 
> > 
> > This seems completely unnecessary. Why would we want to reflect in our changelog that we changed the favicon? This doesn't seem useful at all to the end user.
> 
> It might indeed not be useful for all end users, however, the changelog is both for the end-user and for our own housekeeping. It gives us an easy way to track changes as well. It's a small effort anyways..

I disagree, I think we should not clutter out changelog with such minor insignificant changes. How do you guys feel about this? @jcoenen96 @wotwot563 @StijnGroenen 

@MaxKorlaar Okido, I will implement your suggestion

**Comment by wotwot563** [comment]
Depends if you do it for everything: css, images, color updates etc then ofcourse icons should be in the changelog

It could be usefull if people want to know when the ui has changed and the icon belongs to the ui

**Comment by StijnGroenen** [comment]
I agree with @MaxKorlaar about the favicon formats. (I personally also use https://realfavicongenerator.net/ for my projects).

A for the changelog, I agree with @Brend-Smits that all changes (even the small ones) should be added to the changelog.

**Comment by rubenb994** [comment]
Changes have been made to support realfavicongenerator. Beside that I updated the changelog since most people seem to agree that this should be in there.

**Pull request merged**
