### PR TITLE
Small bugfixes

### PR DESCRIPTION
**Pull request by Yuqera**
Fixed up some small bugfixes:
 - Alerts go away automatically
 - Edit contributors don't overflow
 - Project overview usernames don't overflow
 - Opening project detail modal doesn't screw up the layout
 - When entering something in the search bar and clicking projects in the navbar, the page reloads.

## Description

A few sentences describing the overall goals of the pull request's commits.

## Type of change

-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

## Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I updated the changelog with an end-user readable description
-   [ ] I assigned this pull request to the correct project board to update the sprint board

## Steps to Test or Reproduce

Outline the steps to test or reproduce the PR here.
These steps will be used during release testing.

1.1 Edit a project
1.2 See the alert on the top of the screen
1.3 Wait 5 seconds till the alert goes away

2.1 Edit a project
2.2 Add a contributor with a long name
2.3 See that the contributor gets hidden with 3 dots

3.1 Go to project overview
3.2 See that long usernames get hidden with 3 dots

4.1 Open a project inside project overview
4.2 Close it
4.3 See that everything is still aligned with each other

## Link to issue
#408, #400, #401, #392, #354 

Closes: #408 #400 #401 #392 #354

### CODE REVIEW

**Comment by Brend-Smits** [comment]
Thanks for the fixes @Yuqera, I tested all of them and they work fine. 
Can you please fix the conflicts? If we can get another review in, we can merge this and get it in with this release

**Review by waltersajtos — APPROVED** [review]
Changes look good to me. Good work!

**Review by juliaslaats — DISMISSED** [review]
Looks good to me too!

**Review by waltersajtos — APPROVED** [review]

**Review by Brend-Smits — APPROVED** [review]
Great!

**Pull request merged**
