### PR TITLE
Feature/451-add-call-to-action-icons

### PR DESCRIPTION
**Pull request by waltersajtos**
## Description

This pull request will automatically add the icons from the design to the call to action button, I also added a hotfix for the wizard where the project could not be uploaded if you didn't add a project icon.

## Type of change

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

## Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [x] I updated the changelog with an end-user readable description
-   [ ] I assigned this pull request to the correct project board to update the sprint board

## Steps to Test or Reproduce

Outline the steps to test or reproduce the PR here.
These steps will be used during release testing.

1. Create a project with a call-to-action
2. Go to the detail page of the created project
3. The call-to-action-button should have an icon on the right

## Link to issue

Closes: #451

### CODE REVIEW

**Comment by waltersajtos** [comment]
I want to add the icons to the wizard too before we merge this. Therefore this is blocked by #449

**Review by RubenFricke — COMMENTED** [review]
Works like a charm. I think the call to action icon class can be stored in the backend as a value so we don't have to use the CallToActionIconsConfig right? I think this would improve scalability.

**Comment by waltersajtos** [comment]
> 
> 
> Works like a charm. I think the call to action icon class can be stored in the backend as a value so we don't have to use the CallToActionIconsConfig right? I think this would improve scalability.

Do you want to implement this in the current pull request or implement this in #454

**Review by RubenFricke — APPROVED** [review]
Alright, let's tackle that in #454. In that issue, we have to update the backend anyway, so I guess we can add this update in the backend as well in the related issue on the backend from #454 .

**Review by niraymak — CHANGES_REQUESTED** [review]
I got an error when opening a project in the project overview with no reference to a call to action.

image

**Comment by waltersajtos** [comment]
> 
> 
> I got an error when opening a project in the project overview with no reference to a call to action.
> 
> image

I will try to reproduce this later, I will let you know what's causing this.

**Review by RubenFricke — APPROVED** [review]

**Review by niraymak — APPROVED** [review]
Good job! 🥇

**Pull request merged**
