### PR TITLE
Bugfix/205 highlight toomuch information

### PR DESCRIPTION
**Pull request by niraymak**
## Description

Changes were made in the backend. See issue 205 in backend repo. 

## Type of change

-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

## Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [x] I updated the changelog with an end-user readable description
-   [x] I assigned this pull request to the correct project board to update the sprint board

## Steps to Test or Reproduce

1.Clone frontend (related branch) and backend.
2.Run postman tests
3. Run frontend and check if highlights on the front page work.

## Link to issue

Closes: issue 205 in backend

### CODE REVIEW

**Review by juliaslaats — CHANGES_REQUESTED** [review]
When I run this I don't see anything at 'highlighted projects' anymore. But also in docker the Identity Server isn't able to run, while that does work with the develop branch of backend.

Not really sure what is going wrong tho, I think that is beyond my expertise :D

**Comment by niraymak** [comment]
> When I run this I don't see anything at 'highlighted projects' anymore. But also in docker the Identity Server isn't able to run, while that does work with the develop branch of backend.
> 
> Not really sure what is going wrong tho, I think that is beyond my expertise :D

@juliaslaats Ah I think my branch on the backend is not yet merged with Brend's changes for IdentityServer with Docker. So that won't work in Docker.
No worries, I will ask someone else to review.

**Review by Niekvandam — APPROVED** [review]
Code looks good, tests are functional

**Comment by Brend-Smits** [comment]
Can be closed due to discussion we had on Teams today.

**Pull request closed without merging**
