### PR TITLE
Feature/285 lighthouse cd

### PR DESCRIPTION
**Pull request by Niekvandam**
## Description

Created a new action for the lighthouse audit. 

This pull request should be blocked until #332 (improving lighthouse score) is ready. Once that pull request is ready this one can be accepted. If done otherwise, everyone creating a pull request will have one failed action in the overview. 

## Type of change

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [X] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

## Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my own code
-   [X] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I updated the changelog with an end-user readable description
-   [ ] I assigned this pull request to the correct project board to update the sprint board

## Steps to Test or Reproduce

Outline the steps to test or reproduce the PR here.
These steps will be used during release testing.

1. Create a pull request to develop
2. Check the lighthouse audit in the actions tab
3. Check if the lighthouse audit is working as expected (warning for potential slow elements etc.)

## Link to issue

Closes: #285

### CODE REVIEW

**Comment by Niekvandam** [comment]
If we don't want this PR to be blocked until I finish the lighthouse-score, we can increase the values in the `budget.json` files, which would also resolve the warning/failing check which is happening rn.

**Comment by Niekvandam** [comment]
I reverted the github lightouse CI back to it's original state after talking with Brent about it. The action gets fired after every push to the develop, I used push because every accepted pull request is seen as a 'push' by github actions. This way, after every push, we will check the staging environment and create a report of it.

**Review by elmiratjee — APPROVED** [review]

**Comment by Brend-Smits** [comment]
Changelog 🙃

**Review by Brend-Smits — APPROVED** [review]
Nice, thanks!

**Review by elmiratjee — APPROVED** [review]

**Pull request merged**
