### PR TITLE
Filter fixes

### PR DESCRIPTION
**Pull request by waltersajtos**
## Description

A few sentences describing the overall goals of the pull request's commits.

## Type of change

-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

## Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have made corresponding changes to the documentation
-   [x] I have added tests that prove my fix is effective or that my feature works
-   [x] I updated the changelog with an end-user readable description
-   [x] I assigned this pull request to the correct project board to update the sprint board

## Steps to Test or Reproduce

Outline the steps to test or reproduce the PR here.
These steps will be used during release testing.

1. Go to the project overview page
2. Fill out the fiter
3. Copy the url
4. Paste the url in a new window

## Link to issue

Closes: #517

### CODE REVIEW

**Review by niraymak — CHANGES_REQUESTED** [review]
It looks like something weird goes on with the URL after editing a project and then selecting the filter options. http://localhost:4200/project/details/25?query=&pagination=12&sortOption=updated,desc&categories=%5B3%5D

**Review by niraymak — DISMISSED** [review]

**Review by RubenFricke — CHANGES_REQUESTED** [review]
Whenever a project modal is opened, and I click on the back button (from the browser), I get navigated to the homepage while a few issues earlier we fixed this by only closing the modal. Could you take a look into this again, please?

Whenever I remove the search query from the search bar on the overview page, no projects get shown. 
image


Everything else works flawlessly, great job! This is going to be a great addition, Walter!

**Review by niraymak — APPROVED** [review]

**Review by RubenFricke — CHANGES_REQUESTED** [review]
Whenever I search for projects in the search bar and select a category in the filter menu, the project should hide that does not have this category I think, but this does not work for me.

image

**Comment by waltersajtos** [comment]
> 
> 
> Whenever I search for projects in the search bar and select a category in the filter menu, the project should hide that does not have this category I think, but this does not work for me.
> 
> image

I get the same behaviour in swagger, seems to be a backend issue.

**Review by niraymak — APPROVED** [review]

**Review by RubenFricke — APPROVED** [review]

**Pull request merged**
