### PR TITLE
Add project images

### PR DESCRIPTION
**Pull request by waltersajtos**
## Description

Project images were planned for a long time in the detail page, this pull request will implement both adding and showing the project images.

## Type of change

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

## Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I updated the changelog with an end-user readable description
-   [x] I assigned this pull request to the correct project board to update the sprint board

## Steps to Test or Reproduce

Outline the steps to test or reproduce the PR here.
These steps will be used during release testing.

1. Create a project with 2 project images
2. Go to the overview page and check if the images are shown properly
3. Edit the project and remove 1 image
4. Go to the overview page and check the other image is still there.
5. Edit the project and add another image
6. Go to the overview page and check if the new image is added.

## Link to issue

Closes: #464 
Closes: #539

### CODE REVIEW

**Review by niraymak — CHANGES_REQUESTED** [review]
Thanks alot for another nice new feature Walter! 🥇 

I had some remarks.

- For some reason when switching from homepage to project overview page it took like 9s to load all projects for me. Anyone else experienced this?

- I would suggest to replace the uploading image wizard page step to be after the upload project icon step.

- I like the new way of uploading a project icon in the edit page. But I think it may be a bit unclear how to delete it. I suggest we create a new issue for it if this would take too much time.

- On the edit project page a loading icon was permanently showing in the edit project button.  
image

- Do you guys think we should give the carrousel buttons a different color? In this case they are not very visible. 
image

- We could improve on how pictures are shown. For example this Delta icon isn't readable when uploaded. I guess we can create a new issue for that.
image

**Comment by waltersajtos** [comment]
> 
> 
> Thanks alot for another nice new feature Walter! 🥇
> 
> I had some remarks.
> 
>     * For some reason when switching from homepage to project overview page it took like 9s to load all projects for me. Anyone else experienced this?
> 
>     * I would suggest to replace the uploading image wizard page step to be after the upload project icon step.
> 
>     * I like the new way of uploading a project icon in the edit page. But I think it may be a bit unclear how to delete it. I suggest we create a new issue for it if this would take too much time.
> 
>     * On the edit project page a loading icon was permanently showing in the edit project button. I think this spinner is nicer than the one we use on other pages 👍
>       image
> 
>     * Do you guys think we should give the carrousel buttons a different color? In this case they are not very visible.
>       image
> 
>     * We could improve on how pictures are shown. For example, this Delta icon isn't readable when uploaded. I guess we can create a new issue for that.
>       image

I fixed the order of the image page and the loading image, both were for debugging purposes that I forgot to change back.

For the carousel buttons, I'm not sure if it makes sense to change them, they are kind of supposed to blend in. And they would be hard to see in a lot of images. 

The location should definitely be fixed, I discussed it with @liekevdvoort already.

I don't think deleting the images should be an issue, most of the target audience should be able to figure it out quite easily. Maybe we can add a footer note how to delete them, I wouldn't change the design or functionality for that. Please let me know if you want to include it in this pull-request.

**Comment by liekevdvoort** [comment]
@niraymak i added a small dropshadow to combat the white background issue
image

Also i changed the carousel to stay in a 16:9 aspect ratio so the image looks the same on all devices

**Review by RubenFricke — CHANGES_REQUESTED** [review]
Whenever I uploaded a project icon in the wizard and reopened the wizard, the project icon remained uploaded (partially). It says skip, but it shows an image as a preview. Is this expected?

image

**Review by niraymak — APPROVED** [review]

**Review by niraymak — APPROVED** [review]

**Review by RubenFricke — APPROVED** [review]
Thanks a lot! Looks good

**Pull request merged**
