### PR TITLE
There is no silent-refresh.html, redirect to auth-callback instead

### PR DESCRIPTION
**Pull request by Brend-Smits**
## Description

Current we are trying to silent refresh using the silent-refresh.html, this does not exist though. The silent refresh can make a call to auth-callback, which does exist.

## Type of change

-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

## Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have made corresponding changes to the documentation
-   [x] I have added tests that prove my fix is effective or that my feature works
-   [x] I updated the changelog with an end-user readable description
-   [x] I assigned this pull request to the correct project board to update the sprint board

## Steps to Test or Reproduce

Outline the steps to test or reproduce the PR here.
These steps will be used during release testing.

1. Open Digital Excellence and log-in
2. Wait for your token to expire, watch the tab and check if it calls for a refresh token

## Link to issue

Closes: #253

### CODE REVIEW

**Comment by rubenb994** [comment]
I will test this later tonight

**Comment by Brend-Smits** [comment]
> I will test this later tonight

Thanks, to make testing easier you can set the access token lifetime to 1 minute instead of 1 hour. You can do this by making this change [here](https://github.com/DigitalExcellence/dex-backend/blob/develop/IdentityServer/Configuration/IdentityConfig.cs#L103): 
`                    AccessTokenLifetime = 60,`

**Comment by Brend-Smits** [comment]
@rubenb994 did you have time to look at this?

**Comment by rubenb994** [comment]
I had some time to look at the issue. It appears that on a login the library gets stuck in a loop resulting in the iframe of the library crashing.  In the screenshot below you can see the output of the logs of the oidc library.
image

I've not been able to find why this is happening, it however means that this should be further tested and improved. While researching this issue I found multiple other issues stating that the problem might be related to IdentityServer: https://github.com/IdentityModel/oidc-client-js/issues/766#issuecomment-617725280

The linked issue also explains how to display the debug info for the oidc client. I pasted those lines in the top part of the constructor of the `auth.service.ts`

**Comment by Brend-Smits** [comment]
> I had some time to look at the issue. It appears that on a login the library gets stuck in a loop resulting in the iframe of the library crashing. In the screenshot below you can see the output of the logs of the oidc library.
> image
> 
> I've not been able to find why this is happening, it however means that this should be further tested and improved. While researching this issue I found multiple other issues stating that the problem might be related to IdentityServer: [IdentityModel/oidc-client-js#766 (comment)](https://github.com/IdentityModel/oidc-client-js/issues/766#issuecomment-617725280)
> 
> The linked issue also explains how to display the debug info for the oidc client. I pasted those lines in the top part of the constructor of the `auth.service.ts`

Thanks for the detailed reply Ruben, I will investigate this issue further when I have time :)

**Comment by Brend-Smits** [comment]
I fixed it! It took a few hours but it should all be working flawlessly now :) 
Backend will also need an update for this though. When testing, make sure that you're running the backend branch: [bugfix/246-silent-refresh](https://github.com/DigitalExcellence/dex-backend/tree/bugfix/246-silent-refresh)

**Comment by rubenb994** [comment]
I have added a commit to fix the issue that the 'Unauthorized' toast would still pop up. The user was getting fetched from the backend without being authenticated causing a 401. The call is now only preformed when the user is authenticated.

**Review by rubenb994 — APPROVED** [review]

**Review by rubenb994 — APPROVED** [review]

**Review by RensvdLinden — APPROVED** [review]

**Pull request merged**
